### ISSUE TITLE
Channels Not Playing Right

### ISSUE THREAD

**Issue by kpirnie** [sonroyaalmerol/m3u-stream-merger-proxy#227]
Have Emby on TV and Tablet.

Was playing IFC on TV.

Tried playing NBC on tablet, and it played... on both the tablet and the TV... in other words, IFC mysteriously became NBC

**Comment by kpirnie** [comment]
And of course, now I am testing on 3 devices, with VLC, IPTV, and Smarters and it's working fine.

It appears to be happenning if 2 devices are playing through Emby only.

**Comment by kpirnie** [comment]
And nothing in logs....

**Comment by sonroyaalmerol** [comment]
Hmmm, interesting. Each shared buffers are identified by the request URL so they shouldn't interfere with each other. Does it consistently do that during your tests?

**Comment by kpirnie** [comment]
Just with emby yes.  but... it didnt do it with emby playing on the tablet and vlc on the tv...

**Comment by shorty789** [comment]
It should be added here that when I switched to "Channel 2" and "Channel 1" started playing in place, it played as expected rather than the endless loop it was originally stuck on.

**Comment by kp-emagine** [comment]
I'm going to test again today...  this time I've added `BUFFER_CHUNK_NUM=8` where-as before I did not have that added to my compose file

**Comment by kpirnie** [comment]
@sonroyaalmerol I'm going to guess that, that was my issue.   I didn't set that new ENV variable to anything when this happened, and now that I have it set I cannt replicate the issue.

I tried the exact same channels, the exact same way and both played fine... then I added a third and all 3played fine as well.

one thing I do notice when debug is on.. there's a metric ton of these:
```2025/02/06 07:30:44 [DEBUG] StartWriter: Read 1420 bytes, err: <nil>
2025/02/06 07:30:44 [DEBUG] Write: Advanced buffer position```

that show up... trying to get a log now and just doing this testing over 5 minutes and my log file is over 8M

**Comment by sonroyaalmerol** [comment]
I'm not going to dismiss this issue just yet since @shorty789 was also experiencing similar bugs. I might have overlooked something with the implementation... I'd appreciate more tests and patterns observed if anything more comes up.

And yes, debug logs are huge now. I was using those to debug stuff myself but didn't bother to remove them. Those lines are normal behavior. I'll probably add a way to adjust log levels instead of an on/off switch for debug logs on the next update.

**Comment by kpirnie** [comment]
> And yes, debug logs are huge now. I was using those to debug stuff myself but didn't bother to remove them. Those lines are normal behavior. I'll probably add a way to adjust log levels instead of an on/off switch for debug logs on the next update.

Yeah, no biggee, i only turned them on to see if anything got caught :)
Wife gets home in a few hours, and she's the "TV Junky" here, so I'll let ya know a bit later on ;) lololol

In the meantime, back on to the sorting for me after a rebase (the last few days I got to jump back into some python stuff for work, but have to catch up with my normal stuff that I let slide for those few days SMH)

**Comment by shorty789** [comment]
As an update, I tried to watch again today, first attempt at loading "channel 1" failed, my second attempt to load a different "channel 2" caused an endless loop of part of the program on "channel 1" to repeat endlessly, despite Plex thinking it was actually watching "channel 2" it didn't break out of that loop at all.

The logs seem a little cluttered at the moment and more difficult to filter through, for now I am going to revert just so I can watch things still but I will look to try and gather some logs in the week next week.

**Comment by sonroyaalmerol** [comment]
Can you guys try out the `dev` image and see if this still happens whenever you're free? If it does, I'd appreciate some logs even with the `DEBUG` disabled. I really have not been able to recreate this issue during my tests 🫤.

**Comment by kpirnie** [comment]
This happenned again.  This time on `:latest` release version.  I am trying to replicate again, this time debug is on.  This time, playing Weather Channel in VLC, and tried to fire up IFC in Emby on my phone.  Weather Channel ended up changing to IFC.

If I can get this to replicate, and get the log, it will take me some time to remove my URL's from the log... so...  please keep this open before closing it ;)

Also to note... it takes 2 times in VLC to load the outputted playlist.  1st time does nothing (in VLC.. in the app it appears to load the input m3u's), second time, all the channels load.

**Comment by kpirnie** [comment]
GOT IT!  Ok.   Log will come tomorrow.... I'm dumping it out to a file now, and will sift through my stream URLs to clean them up

**Comment by kpirnie** [comment]
@sonroyaalmerol 
I see where it happens in the log too.  It's some kind of miss or overflow in the buffer

```2025/02/10 21:05:07 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/10 21:05:07 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/10 21:05:07 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/10 21:05:07 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/10 21:05:07 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/10 21:05:07 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/10 21:05:07 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/10 21:05:07 [DEBUG] StartWriter: Read 68808 bytes, err: <nil>
2025/02/10 21:05:07 [DEBUG] Write: Advanced buffer position
2025/02/10 21:05:07 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/10 21:05:07 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/10 21:05:07 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/10 21:05:07 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/10 21:05:07 [DEBUG] Write: Advanced buffer position
2025/02/10 21:05:07 [DEBUG] Write: Setting error state: err=EOF, status=2```

Attached the log... sorry mate, but I kept all the buffer debug stuff in there, in case it points you to something I'm blind to... Also removed all the M3U parsing lines, as it had all of my providers in it ;)   PM me on discord if you want my M3U file.

[kpm_lp-log.zip](https://github.com/user-attachments/files/18749700/kpm_lp-log.zip)

**Comment by sonroyaalmerol** [comment]
AH! I actually see where the problem is now. I'll work on it as soon as I have the time. That helped a lot. Thanks!

**Comment by sonroyaalmerol** [comment]
@kpirnie try out #237. It's a relatively small one but that might be the fix. I can't really test it right now as I just did the PR on the go 🤣

**Comment by kpirnie** [comment]
> [@kpirnie](https://github.com/kpirnie) try out [#237](https://github.com/sonroyaalmerol/m3u-stream-merger-proxy/pull/237). It's a relatively small one but that might be the fix. I can't really test it right now as I just did the PR on the go 🤣

Will do in a little bit bud :)  Gotta do some work ;)
Will keep ya posted though.

**Comment by kpirnie** [comment]
Sorry mate, I just tested one of my channels that I know is an issue, and the failover is not working now.  It just does nothing for a few minutes, then attempts other streams in the group... but never ends up playing. 

I'll try the 2 channels I was playing with last night and see what happens now.

**Comment by kpirnie** [comment]
Yeah, nothing is playing now.  And this is with VLC.

Top of the play attempt is this:

```2025/02/11 09:09:51 [INFO] Client registered (CBS Hartford). Total clients: 1
2025/02/11 09:09:51 [DEBUG] Client registered: 192.168.2.6:55367, count: 1
2025/02/11 09:09:51 [DEBUG] StartWriter: Beginning read loop
2025/02/11 09:09:51 [INFO] Updated connections for M3U_2: 1/5
2025/02/11 09:09:51 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/11 09:09:51 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/11 09:09:51 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/11 09:09:51 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/11 09:09:51 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/11 09:09:51 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/11 09:09:51 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/11 09:09:51 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/11 09:09:51 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/11 09:09:51 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/11 09:09:51 [DEBUG] StartWriter: Read 0 bytes, err: EOF
2025/02/11 09:09:51 [DEBUG] Write: Advanced buffer position
2025/02/11 09:09:51 [DEBUG] Write: Setting error state: err=EOF, status=2
2025/02/11 09:09:51 [INFO] Updated connections for M3U_2: 0/5
2025/02/11 09:09:51 [INFO] Client unregistered (CBS Hartford). Remaining clients: 0```

I can get  you more of the log, but there's some weird loop that seems to happen now once it finally tries other streams

**Comment by sonroyaalmerol** [comment]
No biggie. At least I was able to limit the scope of the problem. I'm pretty sure we're getting close. I'll do more work on this when I have longer time to zone in

**Comment by sonroyaalmerol** [comment]
Can you try it again with the same image when you're free @kpirnie? It should now be working (at least during my own tests).

**Comment by kpirnie** [comment]
> Can you try it again with the same image when you're free [@kpirnie](https://github.com/kpirnie)? It should now be working (at least during my own tests).

will do in a bit mate.   keep ya posted

**Comment by kpirnie** [comment]
off the bat:

> Also to note... it takes 2 times in VLC to load the outputted playlist. 1st time does nothing (in VLC.. in the app it appears to load the input m3u's), second time, all the channels load.

Still happens. I have to load the playlist twice before any channel shows.

Testing the rest now.

**Comment by sonroyaalmerol** [comment]
I'm closing this issue. Will reopen if the problem persists on the latest versions.

**Comment by hosseinsalemi** [comment]
Same bug on 0.21.1

**Comment by sonroyaalmerol** [comment]
@hosseinsalemi I can't help you without any context. At least give me with something to work with (compose file, debug logs when it happens, etc.). I can only fix something if I'm able to recreate it.
